site_name: Lanarky
site_url: https://lanarky.ajndkr.com/
site_author: Ajinkya Indulkar
site_description: The web framework for building LLM microservices
repo_name: ajndkr/lanarky
repo_url: https://github.com/ajndkr/lanarky
copyright: Copyright &copy; 2023 Ajinkya Indulkar

edit_uri: ""

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: lanarky
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/icon.svg
  favicon: assets/favicon.png
  language: en
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Lanarky: index.md
  - Getting Started: getting-started.md
  - Learn:
      - learn/index.md
      - Streaming: learn/streaming.md
      - WebSockets: learn/websockets.md
      - Adapters:
          - learn/adapters/index.md
          - OpenAI:
              - learn/adapters/openai/index.md
              - learn/adapters/openai/streaming.md
              - learn/adapters/openai/websockets.md
              - learn/adapters/openai/router.md
              - learn/adapters/openai/dependencies.md
          - LangChain:
              - learn/adapters/langchain/index.md
              - learn/adapters/langchain/callbacks.md
              - learn/adapters/langchain/streaming.md
              - learn/adapters/langchain/websockets.md
              - learn/adapters/langchain/router.md
              - learn/adapters/langchain/dependencies.md
  - Deployment:
      - deployment/index.md
      - deployment/docker.md
      - GCP: deployment/gcp.md

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ajndkr
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/lanarky/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LanarkyAPI

extra_css:
  - stylesheets/extra.css

plugins:
  - termynal
